export default {
    name: "",
    gender: "",
    class: "",
    subclass: "",
    race: "",
    subrace: "",
    alignment: "",
    background: "",
    experiencePoints: "",
    level: "",
    playerName: "",
    strenth: "",
    strengthProficient: "",
    strengthAdvantage: "",
    strengthDisadvantage: "",
    strengthSaveProficient: "",
    strengthSaveAdvantage: "",
    strengthSaveDisadvantage: "",
    dexterity: "",
    constitution: "",
    intelligence: "",
    wisdom: "",
    charisma: "",
    inspiration: false
};
