export default {
    name: "",
    gender: "",
    size: "",
    lineage: "",
    archetypes: "",
    heritage: "",
    speed: "",
    movement: "",
    stamina: "",
    skills: [
        { name: "punch", proficency: "4" },
        { name: "kick", proficency: "2" },
    ],
    traits: [],
    ethos: "",
    reputation: "",
    experience: "",
    level: "",
    inspiration: "",
};
